

# Visualization
visualize_skeleton: True
visualize_obj: False
visualize_rgb: False

# Dataset
dataset_path: /media/zhihao/Chi_SamSungT7/KIT_Bimanual
obj_path: 2d_object
db_filename: ikea_annotation_db_full
camera: dev3
pose_relative_path: body_pose
train_filename: train_cross_subject.txt

with_obj: True

# Setting
load_mode: img
input_type: rgb
logdir: ./log/EGCN_50_w_obj_A_ooh_kit

#Dataloader
frame_skip: 1
batch_size: 32
frames_per_clip: 50

# Model
arch: EGCN  #architechture

model_args:
  layout: KIT_object_object_hand
  data_shape: [3, 5, 50, 31, 1]
  stem_channel: 64
  block_args: [[48,1,0.5],[24,1,0.5],[64,2,1],[128,2,1]]
  fusion_stage: 2
  act_type: swish
  att_type: stja
  layer_type: SG
  drop_prob: 0.7
  kernel_size: [5,2]
  scale_args: [1.2,1.35]
  expand_ratio: 2
  reduct_ratio: 4
  bias: True
  edge: True
  scale_factor: 5
  custom_A: True



# Optimizer
# SGD, Adam
optimizer: SGD
optimizer_args:
  SGD:
    lr: 0.1
    momentum: 0.9
    nesterov: True
    weight_decay: 0.0001
  Adam:
    lr: 0.01
    betas: [0.9,0.99]
    weight_decay: 0.0001

# Scheduler
# step, cosine
lr_scheduler: MultiStepLR
scheduler_args:
  cosine:
    max_epoch: 70
    warm_up: 10
  MultiStepLR:
    milestones: [5, 10, 15, 20, 25, 30, 50, 70, 90]
    gamma: 0.6

# Training
n_epochs: 300
steps_per_update: 1
refine: False
refine_epoch: 0
gpu_idx: 0